---
- name: "Cordon & Drain {{ inventory_hostname }}"
  ansible.builtin.include_tasks: drain_node.yml

- name: "Upgrade Operating System of {{ inventory_hostname }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  args:
    apply:
      become: yes

- name: "Uncordon {{ inventory_hostname }}"
  ansible.builtin.include_tasks: uncordon_node.yml
