---
- name: Prelim | Include Vaulted Variables
  ansible.builtin.include_vars: vault.yml

- name: "Prelim | Verify need-restarting Command is Present on {{ inventory_hostname }}"
  ansible.builtin.dnf:
    name: dnf-utils
    state: present
  become: true
  when:
    - ansible_os_family == 'RedHat'

- name: "Cordon & Drain {{ inventory_hostname }}"
  ansible.builtin.include_tasks: drain_node.yml

- name: "Upgrade Operating System of {{ inventory_hostname }}"
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
  args:
    apply:
      become: true

- name: Notify Discord
  ansible.builtin.include_tasks: notify_discord.yml

- name: "Uncordon {{ inventory_hostname }}"
  ansible.builtin.include_tasks: uncordon_node.yml
