---
- name: "Update APT Cache on {{ inventory_hostname }}"
  ansible.builtin.apt:
    update_cache: yes

- name: "Update all APT packages on {{ inventory_hostname }}"
  ansible.builtin.apt:
    name: "*"
    state: latest
  register: apt_results

- name: "Send Notification to Discord that {{ inventory_hostname }} was Patched"
  community.general.discord:
    webhook_id: "{{ discord_webhook_id }}"
    webhook_token: "{{ discord_webhook_token }}"
    embeds:
      - title: "👍 {{ inventory_hostname }} was patched 👍"
        color: 1127128
        fields:
          - name: Hostname
            value: "{{ inventory_hostname }}"
          - name: IP Address
            value: "{{ ansible_host }}"
  when:
    - apt_results.changed

- name: "Send Notification to Discord that {{ inventory_hostname }} was Not Patched"
  community.general.discord:
    webhook_id: "{{ discord_webhook_id }}"
    webhook_token: "{{ discord_webhook_token }}"
    embeds:
      - title: "👍 No Patches were Required on {{ inventory_hostname }} 👍"
        color: 65280
        fields:
          - name: Hostname
            value: "{{ inventory_hostname }}"
          - name: IP Address
            value: "{{ ansible_host }}"
  when:
    - not dnf_results.changed

- name: Check if a Reboot is Required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: "Reboot the {{ inventory_hostname }}"
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.stat.exists
