---
- name: "Update all APT packages on {{ inventory_hostname }}"
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
    force_apt_get: true

- name: Check if a Reboot is Required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: "Reboot the {{ inventory_hostname }}"
  ansible.builtin.reboot:
    post_reboot_delay: 30
  when: reboot_required.stat.exists
