galaxy_info:
  author: Chad Zimmerman
  description: Ansible Role for Patching the underlying OS of the K8s Cluster
  company: PrymalNet

  license: MIT

  min_ansible_version: '2.10'

  platforms:
    - name: Fedora
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - patching

dependencies:
  - community.general
  - kubernetes.core
